/**
 * Blog Data Access Layer
 * 
 * Edge Runtime compatible - uses static data generated at build time
 * instead of reading markdown files with fs/path APIs.
 * 
 * Blog posts are generated by scripts/generate-blog-data.ts during build.
 * This ensures compatibility with Cloudflare Pages Edge Runtime.
 */

// Import static blog data (generated at build time)
import { 
  getAllBlogPosts as getAllBlogPostsStatic, 
  getBlogPost as getBlogPostStatic, 
  BlogPost 
} from '@/app/data/blog-posts';

// Re-export the interface for backwards compatibility
export type { BlogPost };

// Define BlogPostMeta interface for SEO and social media metadata
// This is used in the generated static data and can be extended
export interface BlogPostMeta {
  keywords?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: string;
  ogType?: string;
  ogSiteName?: string;
  twitterCard?: string;
  twitterTitle?: string;
  twitterDescription?: string;
  twitterImage?: string;
  twitterCreator?: string;
  articleAuthor?: string;
  articlePublishedTime?: string;
  articleModifiedTime?: string;
  articleSection?: string;
  articleTags?: string[];
  canonicalUrl?: string;
  robots?: string;
  author?: string;
  geoRegion?: string;
  geoPlacename?: string;
  geoPosition?: string;
  ICBM?: string;
}

/**
 * Get all blog posts for a locale
 * Edge Runtime compatible - uses static data
 */
export function getAllBlogPosts(locale: string = 'tr'): BlogPost[] {
  return getAllBlogPostsStatic(locale);
}

/**
 * Get a single blog post by slug
 * Edge Runtime compatible - uses static data
 */
export function getBlogPost(slug: string, locale: string = 'tr'): BlogPost | undefined {
  return getBlogPostStatic(slug, locale);
}

/**
 * Find the corresponding blog post slug in another locale by matching date
 * This assumes that blog posts with the same date are translations of each other
 * Edge Runtime compatible - uses static data only (no fs/path APIs)
 */
export function getCorrespondingBlogSlug(
  currentSlug: string, 
  currentLocale: string, 
  targetLocale: string
): string | undefined {
  // Get current blog post from static data
  const currentPost = getBlogPost(currentSlug, currentLocale);
  if (!currentPost) {
    return undefined;
  }

  // Get all posts in target locale from static data
  const targetPosts = getAllBlogPosts(targetLocale);
  
  // Find post with matching date
  const correspondingPost = targetPosts.find(post => post.date === currentPost.date);
  
  return correspondingPost?.slug;
}

